function interface(Ain,Ad,fin,fd,R,C,N)
figure('Name','PWM Generator','NumberTitle','off',...
       'Units','normalized',...
       'Position',[0.1 0.1 0.8 0.8]);
   
% pushbuttons
uicontrol('Style','pushbutton',...
 'Units','normalized',...
 'Position',[0.05 0.15 0.12 0.05],...
 'backgroundcolor',[0.5 0.5 0.9],...
 'String','Electrical graphic',...
 'Callback','run schema.m');

uicontrol('Style','pushbutton',...
 'Units','normalized',...
 'Position',[0.18 0.05 0.12 0.05],...
 'backgroundcolor',[0.7 0.9 0.7],...
 'String','Exit',...
 'Callback','close all');

uicontrol('Style','pushbutton',...
 'Units','normalized',...
 'Position',[0.05 0.05 0.12 0.05],...
 'backgroundcolor',[0.2 0.35 0.1],...
 'String','Documentation',...
 'Callback',@documentation);
    function documentation(~,~)
   winopen('PWMgenerator.pptx');
end

% titlu
uicontrol('Style','text', ...
           'Units','normalized', ...
           'backgroundcolor',[0.2 0.65 0.7],...
           'Position',[0.10 0.9 0.30 0.1], ...
           'String','PWM Generator','fontsize',14);
       
% text buttons      
uicontrol('Style','text',...
           'Units','normalized', ...
           'Position',[0.1 0.81 0.05 0.05],...
           'backgroundcolor',[0.37 0.93 0.83],...
           'String','Ain=');
uicontrol('Style','text', ...
           'Units','normalized', ...
           'Position',[0.1 0.77 0.05 0.05], ...
           'backgroundcolor',[0.37 0.93 0.83],...
           'String','Ad=');
uicontrol('Style','text', ...
           'Units','normalized', ...
           'Position',[0.1 0.73 0.05 0.05], ...
           'backgroundcolor',[0.37 0.93 0.83],...
           'String','fin=');
uicontrol('Style','text', ...
           'Units','normalized', ...
           'Position',[0.1 0.69 0.05 0.05], ...
           'backgroundcolor',[0.37 0.93 0.83],...
           'String','fd=');
uicontrol('Style','text', ...
           'Units','normalized', ...
           'Position',[0.2 0.81 0.05 0.05], ...
           'backgroundcolor',[0.37 0.93 0.83],...
           'String','R=');
uicontrol('Style','text', ...
           'Units','normalized', ...
           'Position',[0.2 0.77 0.05 0.05], ...
           'backgroundcolor',[0.37 0.93 0.83],...
           'String','C=');
uicontrol('Style','text', ...
           'Units','normalized', ...
           'Position',[0.2 0.73 0.05 0.05], ...
           'backgroundcolor',[0.37 0.93 0.83],...
           'String','N=');


% edit buttons
uicontrol('Style','edit', ...
           'Units','normalized', ...
           'Position',[0.15 0.82 0.05 0.05], ...
           'String',num2str(Ain),...
           'Callback','Ain=str2num(get(gco,''String'')); close all; interface(Ain,Ad,fin,fd,R,C,N)');
uicontrol('Style','edit', ...
           'Units','normalized', ...
           'Position',[0.15 0.78 0.05 0.05], ...
           'String',num2str(Ad),...
           'Callback','Ad=str2num(get(gco,''String'')); close all; interface(Ain,Ad,fin,fd,R,C,N)');
uicontrol('Style','edit', ...
           'Units','normalized', ...
           'Position',[0.15 0.74 0.05 0.05], ...
           'String',num2str(fin),...
           'Callback','fin=str2num(get(gco,''String'')); close all; interface(Ain,Ad,fin,fd,R,C,N)');
uicontrol('Style','edit', ...
           'Units','normalized', ...
           'Position',[0.15 0.70 0.05 0.05], ...
           'String',num2str(fd),...
           'Callback','fd=str2num(get(gco,''String'')); close all; interface(Ain,Ad,fin,fd,R,C,N)');
uicontrol('Style','edit', ...
           'Units','normalized', ...
           'Position',[0.25 0.82 0.05 0.05], ...
           'String',num2str(R),...
           'Callback','R=str2num(get(gco,''String'')); close all; interface(Ain,Ad,fin,fd,R,C,N)');
uicontrol('Style','edit', ...
           'Units','normalized', ...
           'Position',[0.25 0.78 0.05 0.05], ...
           'String',num2str(C),...
           'Callback','C=str2num(get(gco,''String'')); close all; interface(Ain,Ad,fin,fd,R,C,N)');
uicontrol('Style','edit', ...
           'Units','normalized', ...
           'Position',[0.25 0.74 0.05 0.05], ...
           'String',num2str(N),...
           'Callback','N=str2num(get(gco,''String'')); close all; interface(Ain,Ad,fin,fd,R,C,N)');

if (Ain>=Ad)
    uicontrol('Style','text', ...
           'Units','normalized', ...
           'Position',[0.30 0.5 0.3 0.1], 'backgroundcolor','r',...
           'String','Insert a value Ain smaller than Ad for better visualisation','fontsize',12,...
           'Callback','close all; interface(Ain,Ad,fin,fd,R,C,N)');
else


w1=2*pi*fin;
w2=2*pi*fd;
T=R*C;
t=0:T/1000:N*T;
% t = 0:0.001:1;
% sinusoidal signal
s1 = Ain.*sin(w1.*t);

% sawtooth signal
tooth = sawtooth(w2.*t);
s2 = Ad.*tooth;

% pwm signal
n = length(s2);
for i = 1:n
    if (s1(i)>=s2(i))
        pwm(i) = 1;
    else
        pwm(i) = 0;
    end
end

% signal plots
subplot(3,3,[2,3]);
plot(t,s1,'r');grid on; hold on;
title("Input signal");
subplot(3,3,[5,6]);
plot(t,s2,'g');grid on;hold on;
title("Impulses");
subplot(3,3,[8,9]);
plot(t,pwm,'b');grid on;hold on;
title("Modulation in pulse width");

% overlapped signal plot
subplot(3,3,4);
plot(t,s1,'r');grid on;
hold on;
plot(t,s2,'g');grid on;
plot(t,pwm,'b');grid on;
hold off;
title("Overlapped signals");
end 
end
